version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-name: "pydantic"
    ignore:
      - dependency-name: "pydantic"
        update-types:
          - "version-update:semver-patch"

