version: 3

tasks:
  validate:
    cmds:
      - uv run ruff check --fix app
      - uv run ruff check --select I --fix app
      - uv run mypy ./app
      - uv run pytest .

  run:
    cmds:
      - uv run python app/main.py
    env:
      PYTHONPATH: .
