name: Validate Python Code

on:
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  validation:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.5.7"
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.13.1 && uv python pin 3.13.1

      - name: Install dependencies
        run: uv sync --dev

      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.29.1

      - name: run task validate
        run: task validate
